In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from sklearn.preprocessing import scale
from sklearn.metrics import mean_squared_error

In [10]:
X=df.loc[:, 'season':'windspeed']
y=df['cnt']
print('X:',X.shape)
display(X.head())
print('y:',y.shape)
print(y.head())

X: (731, 11)

,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed
0,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446
1,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539
2,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309
3,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296
4,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900

y: (731,)
0     985
1     801
2    1349
3    1562
4    1600
Name: cnt, dtype: int64

In [11]:
csv_in="data/day.csv"
df=pd.read_csv(csv_in, skiprows=0, header=0)
print(df.shape)
print(df.info())
display(df.head())

(731, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     731 non-null    int64
 1   dteday      731 non-null    object
 2   season      731 non-null    int64
 3   yr          731 non-null    int64
 4   mnth        731 non-null    int64
 5   holiday     731 non-null    int64
 6   weekday     731 non-null    int64
 7   workingday  731 non-null    int64
 8   weathersit  731 non-null    int64
 9   temp        731 non-null    float64
 10  atemp       731 non-null    float64
 11  hum         731 non-null    float64
 12  windspeed   731 non-null    float64
 13  casual      731 non-null    int64
 14  registered  731 non-null    int64
 15  cnt         731 non-null    int64
dtypes: float64(4), int64(11), object(1)
memory usage: 91.5+ KB
None

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [12]:
df['season']=df['season'].astype('category')
df['mnth']=df['mnth'].astype('category')
df['weekday']=df['weekday'].astype('category')
df['weathersit']=df['weathersit'].astype('category')

In [13]:
X_dumm=pd.get_dummies(X, drop_first=True)
print('X_dumm:',X_dumm.shape)
display(X_dumm.head())

X_dumm: (731, 29)

,yr,holiday,workingday,temp,atemp,hum,windspeed,season_2,season_3,season_4,...,mnth_11,mnth_12,weekday_1,weekday_2,weekday_3,weekday_4,weekday_5,weekday_6,weathersit_2,weathersit_3
0,0,0,0,0.344167,0.363625,0.805833,0.160446,0,0,0,...,0,0,0,0,0,0,0,1,1,0
1,0,0,0,0.363478,0.353739,0.696087,0.248539,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,1,0.196364,0.189405,0.437273,0.248309,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,0,0,1,0.200000,0.212122,0.590435,0.160296,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,0,0,1,0.226957,0.229270,0.436957,0.186900,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [14]:
X_dumm_c=sm.add_constant(X_dumm)
model=sm.OLS(y, X_dumm_c)
results=model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    cnt   R-squared:                       0.848
Model:                            OLS   Adj. R-squared:                  0.842
Method:                 Least Squares   F-statistic:                     140.3
Date:                Thu, 08 Jun 2023   Prob (F-statistic):          8.67e-266
Time:                        15:20:15   Log-Likelihood:                -5880.2
No. Observations:                 731   AIC:                         1.182e+04
Df Residuals:                     702   BIC:                         1.195e+04
Df Model:                          28
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const         1485.8439    239.746      6.198      0.000    1015.138    1956.550
yr            2019.7354     58.220     34.691      0.000    1905.429    2134.042
holiday       -258.8454    160.940     -1.608      0.108    -574.827      57.136
workingday     330.8518     66.825      4.951      0.000     199.651     462.053
temp          2855.0107   1398.156      2.042      0.042     109.942    5600.079
atemp         1786.1574   1462.120      1.222      0.222   -1084.494    4656.808
hum          -1535.4684    292.448     -5.250      0.000   -2109.646    -961.290
windspeed    -2823.2967    414.552     -6.810      0.000   -3637.207   -2009.386
season_2       884.7108    179.492      4.929      0.000     532.305    1237.117
season_3       832.7022    213.129      3.907      0.000     414.255    1251.150
season_4      1575.3506    181.001      8.704      0.000    1219.983    1930.718
mnth_2         131.0251    143.776      0.911      0.362    -151.258     413.308
mnth_3         542.8277    165.433      3.281      0.001     218.025     867.630
mnth_4         451.1656    247.567      1.822      0.069     -34.895     937.226
mnth_5         735.5055    267.628      2.748      0.006     210.059    1260.952
mnth_6         515.4048    282.411      1.825      0.068     -39.066    1069.876
mnth_7          30.7966    313.821      0.098      0.922    -585.343     646.937
mnth_8         444.9490    303.165      1.468      0.143    -150.270    1040.168
mnth_9        1004.1728    265.123      3.788      0.000     483.644    1524.701
mnth_10        519.6743    241.554      2.151      0.032      45.420     993.928
mnth_11       -116.6933    230.776     -0.506      0.613    -569.788     336.401
mnth_12        -89.5915    182.214     -0.492      0.623    -447.342     268.159
weekday_1     -118.7980     71.469     -1.662      0.097    -259.116      21.520
weekday_2      -21.3242     77.324     -0.276      0.783    -173.138     130.490
weekday_3       50.5056     77.670      0.650      0.516    -101.988     202.999
weekday_4       55.4911     77.017      0.721      0.471     -95.721     206.703
weekday_5      106.1319     77.308      1.373      0.170     -45.652     257.915
weekday_6      440.4588    106.562      4.133      0.000     231.240     649.678
weathersit_2  -462.5381     77.087     -6.000      0.000    -613.887    -311.190
weathersit_3 -1965.0865    197.052     -9.972      0.000   -2351.968   -1578.205
==============================================================================
Omnibus:                      125.281   Durbin-Watson:                   1.198
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              347.309
Skew:                          -0.860   Prob(JB):                     3.83e-76
Kurtosis:                       5.906   Cond. No.                     1.45e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.12e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [15]:
print('Adj R2:', results.rsquared_adj)

Adj R2: 0.8423198263206381

In [16]:
print(results.params)

const           1485.843924
yr              2019.735428
holiday         -258.845357
workingday       330.851836
temp            2855.010723
atemp           1786.157384
hum            -1535.468444
windspeed      -2823.296680
season_2         884.710812
season_3         832.702216
season_4        1575.350641
mnth_2           131.025127
mnth_3           542.827731
mnth_4           451.165624
mnth_5           735.505485
mnth_6           515.404791
mnth_7            30.796641
mnth_8           444.948954
mnth_9          1004.172834
mnth_10          519.674276
mnth_11         -116.693280
mnth_12          -89.591499
weekday_1       -118.797973
weekday_2        -21.324201
weekday_3         50.505588
weekday_4         55.491133
weekday_5        106.131932
weekday_6        440.458840
weathersit_2    -462.538127
weathersit_3   -1965.086545
dtype: float64

In [22]:
X_scaled_ar=scale(X_dumm)
y_scaled_ar=scale(y)
X_scaled=pd.DataFrame(X_scaled_ar, columns=X_dumm.columns)
y_scaled=pd.Series(y_scaled_ar, name=y.name)
model=sm.OLS(y_scaled, X_scaled)
results_scaled=model.fit()
print(results_scaled.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                    cnt   R-squared (uncentered):                   0.848
Model:                            OLS   Adj. R-squared (uncentered):              0.842
Method:                 Least Squares   F-statistic:                              140.5
Date:                Thu, 08 Jun 2023   Prob (F-statistic):                   3.49e-266
Time:                        15:32:28   Log-Likelihood:                         -347.82
No. Observations:                 731   AIC:                                      751.6
Df Residuals:                     703   BIC:                                      880.3
Df Model:                          28
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
yr               0.5217      0.015     34.542      0.000       0.492       0.551
holiday      -1.453e+08   8.57e+11     -0.000      1.000   -1.68e+12    1.68e+12
workingday   -4.044e+08   2.39e+12     -0.000      1.000   -4.69e+12    4.68e+12
temp             0.2698      0.132      2.039      0.042       0.010       0.530
atemp            0.1503      0.123      1.220      0.223      -0.092       0.392
hum             -0.1129      0.021     -5.254      0.000      -0.155      -0.071
windspeed       -0.1129      0.017     -6.812      0.000      -0.145      -0.080
season_2         0.1983      0.040      4.932      0.000       0.119       0.277
season_3         0.1880      0.048      3.910      0.000       0.094       0.282
season_4         0.3493      0.040      8.708      0.000       0.271       0.428
mnth_2           0.0181      0.020      0.906      0.365      -0.021       0.057
mnth_3           0.0781      0.024      3.252      0.001       0.031       0.125
mnth_4           0.0640      0.035      1.821      0.069      -0.005       0.133
mnth_5           0.1059      0.039      2.749      0.006       0.030       0.181
mnth_6           0.0731      0.040      1.820      0.069      -0.006       0.152
mnth_7           0.0044      0.045      0.098      0.922      -0.084       0.093
mnth_8           0.0640      0.044      1.468      0.143      -0.022       0.150
mnth_9           0.1424      0.038      3.783      0.000       0.068       0.216
mnth_10          0.0748      0.035      2.142      0.032       0.006       0.143
mnth_11         -0.0165      0.033     -0.505      0.614      -0.081       0.048
mnth_12         -0.0129      0.026     -0.491      0.624      -0.064       0.039
weekday_1      3.05e+08    1.8e+12      0.000      1.000   -3.53e+12    3.53e+12
weekday_2     3.038e+08   1.79e+12      0.000      1.000   -3.52e+12    3.52e+12
weekday_3     3.038e+08   1.79e+12      0.000      1.000   -3.52e+12    3.52e+12
weekday_4     3.038e+08   1.79e+12      0.000      1.000   -3.52e+12    3.52e+12
weekday_5     3.038e+08   1.79e+12      0.000      1.000   -3.52e+12    3.52e+12
weekday_6        0.0798      0.019      4.135      0.000       0.042       0.118
weathersit_2    -0.1130      0.019     -6.004      0.000      -0.150      -0.076
weathersit_3    -0.1696      0.017     -9.977      0.000      -0.203      -0.136
==============================================================================
Omnibus:                      125.387   Durbin-Watson:                   1.198
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              347.146
Skew:                          -0.861   Prob(JB):                     4.15e-76
Kurtosis:                       5.904   Cond. No.                     6.17e+14
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The smallest eigenvalue is  7e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [23]:
print(results_scaled.params.sort_values(key=np.abs,ascending=False))

workingday     -4.043518e+08
weekday_1       3.050354e+08
weekday_5       3.038218e+08
weekday_4       3.038218e+08
weekday_3       3.038218e+08
weekday_2       3.038218e+08
holiday        -1.452805e+08
yr              5.216564e-01
season_4        3.492632e-01
temp            2.697772e-01
season_2        1.983383e-01
season_3        1.880058e-01
weathersit_3   -1.695599e-01
atemp           1.502530e-01
mnth_9          1.423794e-01
weathersit_2   -1.130113e-01
windspeed      -1.129455e-01
hum            -1.128919e-01
mnth_5          1.058515e-01
weekday_6       7.979757e-02
mnth_3          7.812151e-02
mnth_10         7.478932e-02
mnth_6          7.307768e-02
mnth_8          6.403542e-02
mnth_4          6.396961e-02
mnth_2          1.814745e-02
mnth_11        -1.654611e-02
mnth_12        -1.289403e-02
mnth_7          4.431576e-03
dtype: float64